// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewczhyengtfouixcazuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3Y3poeWVuZ3Rmb3VpeGNhenV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzMzOTEsImV4cCI6MjA3MjY0OTM5MX0.tSoz5VN-IoBX4sECwXIQu5gbC4bea8XH60j-QTbelas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});